language: node_js
node_js:
- stable
- '4'
- '5'
- '6'
before_install:
- npm install -g typings
- npm install -g codeclimate-test-reporter
- typings install
after_success:
- codeclimate-test-reporter < coverage/PhantomJS*/lcov.info
